### ISSUE TITLE
Always responding with "i dont know"

### ISSUE THREAD

**Issue by jafioti** [fawazsammani/chatbot-transformer#1]
Hi,
I have tried to train a model with your code and the cornell movie dialogue dataset, and after training for 9 epochs, the only thing it outputs is "i dont know" regardless of input. Not sure if you are seeing the same thing.

**Comment by fawazsammani** [comment]
this problem used to happen in the old version because the masks were wrong. But i have corrected it in some previous commit if i recall correctly. The problem isnt happening anymore and the output is quite good.

**Comment by huwprosser** [comment]
Hi there, after 8 epochs the bot is still saying "I don't know" despite being on latest commit.
